### ISSUE TITLE
JACK/LV2 CV support?

### ISSUE THREAD

**Issue by mxmilkiib** [midilab/opendsp#1]
All the details [here](https://linuxmusicians.com/viewtopic.php?f=1&t=20701). I guess it could factor into OpenDSP some day?

**Comment by midilab** [comment]
What do you want to achieve? Integrate LV2 into a real modular CV setup? How much resolution do you need? There are some ways to achieve such a quest, and one of the goals of OpenDSP is to get a smooth as possible CV integration some day for sure. 
But it really force us on a solution that is dependent on a extended hardware(MIDI/CV, SPI/CV, ANY*/CV) to convert signals between LV2 and your modular. 
MIDI/CV its the most affordable solution, but you get your self stuck into the low MIDI resolution of CC messages or note range within 12 notes temperament only and makes you not able to use the potential of LV2/CV metadata ports with your modular setup.
SPI/CV can give you a quite good signal resolution to work directly with LV2/CV metadata ports conversion.
No experience from my side of other methods avaliable to work with LV2/CV using only the native hardware of PC/Embeded devices.
From the point of view of OpenDSP about support to integrate such of interfaces, goes only on driver level for a SPI/CV converter in that case - i do have plans to make a hardware interface for that matter. MIDI/CV converters are supported by default.
Nice compilation of info about the subject you have on the link by the way...

**Comment by mxmilkb** [comment]
Yes to create a hybrid modular setup. 32 bit float PCM, though I guess a step down to a [lower bitrate](http://bytenoise.co.uk/Choosing_a_DAC_for_Control_Voltages) as an option if the hardware is not available?

Hardware is certainly a limiting factor, though there are [options](https://www.youtube.com/watch?v=VEXiezcEOU4) for AC-coupled audio interfaces. See also [mod-spi2jack](https://github.com/moddevices/mod-spi2jack). And thanks :)

**Comment by midilab** [comment]
For linux, a standard way to go is the [IIO](https://wiki.analog.com/software/linux/docs/iio/iio), this is what the guys from MOD Devices are using on their Duo X for 2 pedal expression and the Soundcard conversions.  
By making use of IIO we have out-of-the-box access for a lot of good, cheap and avaliable on the market DACs/ADCs for our modular/computer integration.  
Im still studing to find the best way to integrate the whole thing with good cost x benefit to keep it DIY friendly.  
Compiling mod-spi2jack was problematic for opendsp for two reasons:  
1) It is jack2 compilant - opendsp uses jack1  
2) Their code is not out-of-the-box made to use with any IIO device, for that to happens it needs some code changes. It was written hardcoded for their Duo machine devices. But it is still manageble to fork their project into a generic IIO2Jack tool instead.  
Any help in development, ideias or support work force it will be great!

**Comment by midilab** [comment]
Hi @mxmilkb !

By continue the saga of being able to use our embedded systems as modular devices for eurorack the release 0.10 are bringing good news about.

OpenDSP 0.10 has support for some of the most common DACs/ADCs on the market, not tested yet but open for tests, suggestions and experiments:

+ ADC
  CC [M]  drivers/iio/adc/ad_sigma_delta.o
  CC [M]  drivers/iio/adc/ad7266.o
  CC [M]  drivers/iio/adc/ad7291.o
  CC [M]  drivers/iio/adc/ad7298.o
  CC [M]  drivers/iio/adc/ad7923.o
  CC [M]  drivers/iio/adc/ad7476.o
  CC [M]  drivers/iio/adc/ad7791.o
  CC [M]  drivers/iio/adc/ad7793.o
  CC [M]  drivers/iio/adc/ad7887.o
  CC [M]  drivers/iio/adc/ad799x.o
  CC [M]  drivers/iio/adc/hi8435.o
  CC [M]  drivers/iio/adc/ina2xx-adc.o
  CC [M]  drivers/iio/adc/ltc2485.o
  CC [M]  drivers/iio/adc/max1027.o
  CC [M]  drivers/iio/adc/max1363.o
  CC [M]  drivers/iio/adc/mcp320x.o
  CC [M]  drivers/iio/adc/mcp3422.o
  CC [M]  drivers/iio/adc/nau7802.o
  CC [M]  drivers/iio/adc/ti-adc081c.o
  CC [M]  drivers/iio/adc/ti-adc0832.o
  CC [M]  drivers/iio/adc/ti-adc12138.o
  CC [M]  drivers/iio/adc/ti-adc128s052.o
  CC [M]  drivers/iio/adc/ti-adc161s626.o
  CC [M]  drivers/iio/adc/ti-ads1015.o
  CC [M]  drivers/iio/adc/ti-ads8688.o
+ DAC
CC [M]  drivers/iio/dac/ad5360.o
  CC [M]  drivers/iio/dac/ad5380.o
  CC [M]  drivers/iio/dac/ad5421.o
  CC [M]  drivers/iio/dac/ad5624r_spi.o
  CC [M]  drivers/iio/dac/ad5064.o
  CC [M]  drivers/iio/dac/ad5504.o
  CC [M]  drivers/iio/dac/ad5446.o
  CC [M]  drivers/iio/dac/ad5449.o
  CC [M]  drivers/iio/dac/ad5592r-base.o
  CC [M]  drivers/iio/dac/ad5592r.o
  CC [M]  drivers/iio/dac/ad5593r.o
  CC [M]  drivers/iio/dac/ad5755.o
  CC [M]  drivers/iio/dac/ad5761.o
  CC [M]  drivers/iio/dac/ad5764.o
  CC [M]  drivers/iio/dac/ad5791.o
  CC [M]  drivers/iio/dac/ad5686.o
  CC [M]  drivers/iio/dac/ad7303.o
  CC [M]  drivers/iio/dac/ad8801.o
  CC [M]  drivers/iio/dac/m62332.o
  CC [M]  drivers/iio/dac/max517.o
  CC [M]  drivers/iio/dac/max5821.o
  CC [M]  drivers/iio/dac/mcp4725.o
  CC [M]  drivers/iio/dac/mcp4922.o
