### ISSUE TITLE
can't use mouse or keyboard

### ISSUE THREAD

**Issue by farvardin** [midilab/opendsp#2]
Hello,

I've put the opendsp_0.9.4-raspberry_pi2_3.img into a 16 Gb sd card in my rpi 3b, connected the hdmi cable, it can boot, I see the "opendsp login", then it automatically loads the graphical interface, I can see a "desktop 1" window, then the screen background is all black with a white arrow mouse cursor. But the keyboard and mouse are not responding, they are even not lighted. The same setup is working with other rpi images (mouse + keyboard). I've tried a 3A psu and other mouse and keyboards, but it's the same.

I can access to the opendsp on my network, anyway.

Maybe some kernel support for mouse and keyboard are disabled to keep opendsp lighter? In this case it could be documented.

**Comment by farvardin** [comment]
I've seen now in the doc: "The main video output normaly accessed via HDMI or DVI port are always dedicated to video projection. In that case you should not be using this display to do management on your app needs, for that matter you have the Virtual Display to be use."

Maybe it could also display the ip address of the device? http://opendsp is not responding when called from a linux computer... (I've discovered the ip address by scanning my network ports)

**Comment by midilab** [comment]
The idea is to keep opendsp like a blackbox to be used as standalone DSPing system(audio or video) that can be controlled using MIDI or OSC protocol. It is still in pre-release state, im working rigth now on a new release, more user oriented for that matter. Like MIDI and OSC docs about how to mapping functions.

About the opendsp network address name, i had miss that point on the doc, i will try to updated with a better approach to find the opendsp over the network, thanks for the feedback by the way.

On day by day usage, i do recommend to use a wifi dongle if you are using a pi2(pi3 has a wifi device integrated) so you can access him like a access point by using your mobile phone for example(quite usefull on performances) with a VNC client.

**Comment by midilab** [comment]
https://github.com/midilab/opendsp/wiki/Network
